name: Ping Replit Daily at 9AM

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 기준 → 한국 오전 9시

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Replit
        run: |
          curl -s https://4f6a249b-41e4-4bb3-bd06-40e0402f16d1-00-3cr5qxfbva3cm.pike.replit.dev/
